- src/main/scala/no/ndla/draftapi/controller/InternController.scala
- src/main/scala/no/ndla/draftapi/model/api/UpdatedAgreement.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/main/scala/no/ndla/draftapi/service/search/IndexService.scala
Fixes bug where updating validFrom and validTo in agreements only
accepted ISO8601 without milliseconds
> #835: Fixes bug with updating dates in agreements

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
Tar inn endringer til license-endepunktet fra article-api. Dette endepunktet fjernes fra article-api
> update license endpoint #840

- build.sbt
- src/main/scala/db/migration/V4__MoveRelatedContentEmbedsToDivs.scala
- src/main/scala/no/ndla/draftapi/JettyLauncher.scala
- src/test/scala/db/migration/V4__MoveRelatedContentEmbedsToDivsTest.scala
resolves https://github.com/NDLANO/Issues/issues/1042
> #1042: Adds migration script for moving related-content embds into divs

- build.sbt
resolves https://github.com/NDLANO/Issues/issues/1055
> #1055: Bump validation to 0.18

- build.sbt
connects https://github.com/NDLANO/Issues/issues/1096
> #1096: Bump validation

- build.sbt
Waiting for: https://github.com/NDLANO/validation/pull/22 and https://github.com/NDLANO/validation/pull/21
> #1096, #1104: Bump validation to 0.21

- build.sbt
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableArticle.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableLanguageFormats.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableLanguageValues.scala
- src/main/scala/no/ndla/draftapi/service/ReadService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
- src/test/scala/no/ndla/draftapi/model/search/SearchableArticleSerializerTest.scala
- src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/search/DraftSearchConverterServiceTest.scala
connects to https://github.com/NDLANO/issues/issues/1058
> #1058: Dynamically adds data-url to file embeds, also converts single embeds to anchors

- src/main/resources/db/migration/V5__ExternalIdAsArray.sql
- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/controller/InternController.scala
- src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- src/main/scala/no/ndla/draftapi/model/domain/package.scala
- src/main/scala/no/ndla/draftapi/repository/ConceptRepository.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
connects to https://github.com/NDLANO/Issues/issues/1146
> #1146: Stores multiple external ids in database

- src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
> update external ids on publish #1152

- src/main/scala/db/migration/V6__MoveToNewFileEmbedFormat.scala
- src/test/scala/db/migration/V6__MoveToNewFileEmbedFormatTest.scala
resolves https://github.com/NDLANO/Issues/issues/1168
> #1168: Adds migration for not storing file-url in database

- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
connects to https://github.com/NDLANO/Issues/issues/1170
> #1170: Fetching externalIds of articles without external ids no longer fails

- src/main/scala/no/ndla/draftapi/integration/Elastic4sClient.scala
connects to https://github.com/NDLANO/Issues/issues/1177
> #1177: Sets longer timeout for elastic4s client

- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/db/migration/V7__AddImageMetaAltText.scala
- src/main/scala/no/ndla/draftapi/model/api/ArticleApiArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/ArticleMetaImage.scala
- src/main/scala/no/ndla/draftapi/model/api/NewArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/NewArticleMetaImage.scala
- src/main/scala/no/ndla/draftapi/model/api/UpdatedArticle.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleContent.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleIntroduction.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleMetaDescription.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleMetaImage.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleTag.scala
- src/main/scala/no/ndla/draftapi/model/domain/ArticleTitle.scala
- src/main/scala/no/ndla/draftapi/model/domain/ConceptContent.scala
- src/main/scala/no/ndla/draftapi/model/domain/ConceptTitle.scala
- src/main/scala/no/ndla/draftapi/model/domain/Language.scala
- src/main/scala/no/ndla/draftapi/model/domain/LanguageField.scala
- src/main/scala/no/ndla/draftapi/model/domain/VisualElement.scala
- src/main/scala/no/ndla/draftapi/model/domain/package.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableLanguageValues.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- src/test/scala/db/migration/V7__AddImageMetaAltTextTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
connects to https://github.com/NDLANO/Issues/issues/1094
> #1094: Adds metaImage altText to articles

- build.sbt
connects to NDLANO/Issues#1300
> #1300: Bump validation

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Fixes NDLANO/issues#1412
* Deletes specified language from article.
> Delete specified language if more than one language

- build.sbt
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
connected to NDLANO/Issues#1439
Avhenger av at https://github.com/NDLANO/network/pull/38 merges før denne bygger
> upgrade network library to 0.36 #1439

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/controller/FileController.scala
- src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
- src/main/scala/no/ndla/draftapi/integration/AmazonClient.scala
- src/main/scala/no/ndla/draftapi/model/api/UploadedFile.scala
- src/main/scala/no/ndla/draftapi/model/domain/FileStream.scala
- src/main/scala/no/ndla/draftapi/model/domain/UploadedFile.scala
- src/main/scala/no/ndla/draftapi/service/FileStorageService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/TestEnvironment.scala
- src/test/scala/no/ndla/draftapi/controller/FileControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/FileStorageServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
connects to NDLANO/Issues#1411
> #1411: Adds file upload endpoint

- build.sbt
- project/plugins.sbt
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/controller/AgreementController.scala
- src/main/scala/no/ndla/draftapi/controller/ConceptController.scala
- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/controller/FileController.scala
- src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
- src/main/scala/no/ndla/draftapi/model/api/ArticleSearchResult.scala
- src/main/scala/no/ndla/draftapi/model/api/ConceptSearchResult.scala
- src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/draftapi/model/api/SearchResult.scala
- src/main/scala/no/ndla/draftapi/model/domain/SearchResult.scala
- src/main/scala/no/ndla/draftapi/service/search/AgreementSearchService.scala
- src/main/scala/no/ndla/draftapi/service/search/ArticleSearchService.scala
- src/main/scala/no/ndla/draftapi/service/search/ConceptSearchService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchService.scala
- src/test/scala/no/ndla/draftapi/consumerdrivencontracts/DraftApiProviderCDCTest.scala
- src/test/scala/no/ndla/draftapi/controller/AgreementControllerTest.scala
- src/test/scala/no/ndla/draftapi/controller/ConceptControllerTest.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/search/AgreementSearchServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/search/ArticleSearchServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/search/ConceptSearchServiceTest.scala
connects to NDLANO/Issues#1489
> #1489: Adds scrolling functionality to search endpoints

- build.sbt
- src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
connects to NDLANO/Issues#1508
> #1508: Bumps validation to 0.30

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/model/api/UpdatedArticle.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
connects to NDLANO/Issues#1365
> 1365#: Add update field in UpdatedArticle

- src/main/scala/db/migration/R__SetArticleTypeFromTaxonomy.scala
- src/test/scala/db/migration/R__SetArticleTypeFromTaxonomyTest.scala
connects to NDLANO/Issues#1530
> #1530: Adds repeatable migration based on taxonomy

- src/main/scala/no/ndla/draftapi/controller/AgreementController.scala
- src/main/scala/no/ndla/draftapi/controller/ConceptController.scala
- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/test/scala/no/ndla/draftapi/controller/AgreementControllerTest.scala
- src/test/scala/no/ndla/draftapi/controller/ConceptControllerTest.scala
Connects to NDLANO/Issues#1476
> #1476: Add access checks

- src/main/scala/no/ndla/draftapi/controller/InternController.scala
- src/main/scala/no/ndla/draftapi/service/search/IndexService.scala
- src/test/scala/no/ndla/draftapi/controller/InternControllerTest.scala
Connects to NDLANO/Issues#1532
> #1532: Add delete index method

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
connects to NDLANO/Issues#1575
> #1575: Automatically detect s3 region

- src/main/scala/db/migration/R__SetArticleLanguageFromTaxonomy.scala
Connects to NDLANO/Issues#1607
> #1607: fix format and url

- src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
Connects to NDLANO/Issues#1615
> #1615: add new version of published article in db

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/integration/SearchApiClient.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/TestEnvironment.scala
> #1676: Send draft to search-api on save for instant indexing

- src/main/scala/db/migration/V18__AddPublishedDate.scala
- src/main/scala/no/ndla/draftapi/model/api/Article.scala
- src/main/scala/no/ndla/draftapi/model/api/ArticleApiArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/NewArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/UpdatedArticle.scala
- src/main/scala/no/ndla/draftapi/model/domain/Content.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/test/scala/db/migration/V18__AddPublishedDateTest.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/integration/ArticleApiClientTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Legger til felt for publisert som kan overstyres fra ed. Oppdatertfeltet skal oppdateres ved kvar lagring.
> Add new published date and always update updated date

- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
Returnerer siste artikkelversjon ved lagring. Fjerner duplikat setting av status.
> Return copied article. Also copy imported article

- src/main/scala/no/ndla/draftapi/service/WriteService.scala
Oppretter note ved opprettelse av artikkel.
> Add note showing created article

- src/main/scala/no/ndla/draftapi/model/api/ArticleSummary.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableArticle.scala
- src/main/scala/no/ndla/draftapi/service/search/ArticleIndexService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
- src/test/scala/no/ndla/draftapi/model/search/SearchableArticleSerializerTest.scala
- src/test/scala/no/ndla/draftapi/service/search/SearchConverterServiceTest.scala
Egentlig usikker på om vi treng å søke etter brukere i draft-api. I search-api er det jo nyttig men kanskje ikkje her. Droppa å legge til søkeparameter i første omgang, men er fort å legge til.
> Add possibility to search for users.

- src/main/scala/no/ndla/draftapi/integration/LearningpathApiClient.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
Depends on https://github.com/NDLANO/learningpath-api/pull/131
Searches learningpath-api for urls used in learningpaths
> Remove fetch all learningpaths and add searching for paths

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/service/ReadService.scala
connects to NDLANO/Issues#1704
> Endpoint for history of article

- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
Import av artikler har ført til revisjon 2 og det er ikkje ønskelig ved import. 
Også setting av System som meldingsforfatter ved import.
> Only one article revision when importing.

- build.sbt
Connects to NDLANO/Issues#1817
> Bump validation library

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Connects to NDLANO/Issues#1829
> Validate on language

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- src/test/scala/no/ndla/draftapi/consumerdrivencontracts/DraftApiProviderCDCTest.scala
Depends on: NDLANO/search-api/pull/80
> #1887: Adds search-api as pact consumer

- src/main/scala/no/ndla/draftapi/model/api/UpdatedArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/package.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
https://github.com/NDLANO/Issues/issues/2011
> added remove metaImage functionality

- src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
Fixes https://github.com/NDLANO/Issues/issues/2052
> #2052: Update taxonomymetadata on unpublish+publish

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/integration/ConceptApiClient.scala
- src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/ReadService.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/TestEnvironment.scala
- src/test/scala/no/ndla/draftapi/integration/ConceptApiClientTest.scala
- src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
> #2053: Publish concepts with QUEUED_FOR_PUBLISHING when publishing drafts

- src/main/scala/no/ndla/draftapi/integration/ConceptApiClient.scala
- src/main/scala/no/ndla/draftapi/service/search/ArticleSearchService.scala
- src/test/scala/no/ndla/draftapi/integration/ConceptApiClientTest.scala
NDLANO/Issues#2103
Bruker korrekt status for publisering.
> Publish concepts with correct status

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
- src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/FileStorageService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
> #2106: Cloning files on article cloning

- src/main/resources/db/migration/V26__CreateArticleIdSequence.sql
- src/main/scala/db/migration/V25__RemoveDomainFromH5PUrl.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
> #2168: Use postgres sequence for deriving new `article_id`'s to avoid race conditions

- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
Publiseringsscript skal kunne publisere fra alle statuser. Enklest då å gjøre dette slik.
> Added possibility to publish from more statuses

- build.sbt
https://github.com/NDLANO/Issues/issues/2233
https://github.com/NDLANO/Issues/issues/1998
> bump validation with updated ol tag and added code-block embed tag

- src/main/scala/no/ndla/draftapi/model/api/ArticleSummary.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
> #2262: Adds tags-field to draft-api/v1/drafts endpoint

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/integration/H5PApiClient.scala
- src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/TestEnvironment.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
Fixes NDLANO/Issues#2283
- Gjør kall til H5P tjenesten assosiert med miljøet for å publisere alle H5P'er som finnes i artikkelen når den publiseres.
> #2283: Publish h5p's in article when publishing

- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
Hører til https://github.com/NDLANO/editorial-frontend/pull/862
Relaterte forklaringer skal publiseres når artikkelen publiseres.
> Publish related concepts when article is published

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
Fixes NDLANO/Issues#2405
En ekstra status for forhåndsvisning.
> Add status for preview without login

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- src/main/scala/no/ndla/draftapi/model/api/PartialPublishArticle.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Partially fixxes https://github.com/NDLANO/Issues/issues/2402
> 2402 utvide partial publish

- build.sbt
Tilhører NDLANO/Issues#2410
Oppdaterer validation-versjon. Se: https://github.com/NDLANO/validation/pull/47
> 2410 inline visning av pdf i artikkel

- src/main/scala/no/ndla/draftapi/integration/ConceptApiClient.scala
- src/test/scala/no/ndla/draftapi/integration/ConceptApiClientTest.scala
Fixes NDLANO/Issues#2431
Automatisk publisering av konsepter tilhørende en artikkel skal begrenses til artikler med status "publiseringsklar" (status="QUALITY_ASSURED"). Har oppdatert tester for å sjekke at artikler uten denne statusen ikke blir publisert.
> Only auto publish concepts with status QUALITY_ASSURED

- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- src/main/scala/no/ndla/draftapi/model/api/Article.scala
- src/main/scala/no/ndla/draftapi/model/api/ArticleApiArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/NewArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/PartialPublishArticle.scala
- src/main/scala/no/ndla/draftapi/model/api/UpdatedArticle.scala
- src/main/scala/no/ndla/draftapi/model/domain/Availability.scala
- src/main/scala/no/ndla/draftapi/model/domain/Content.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableLanguageFormats.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/integration/ArticleApiClientTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
https://github.com/NDLANO/Issues/issues/2414
> 2414 utvide artikkel med et ekstra felt

- src/main/scala/no/ndla/draftapi/controller/InternController.scala
Fikser enum serializer for availability feltet i InternalController
> add availability enum serializer in internalController

- build.sbt
Klarte å reprodusere lokalt (og dette fikser det lokalt i alle fall)
Hadde kanskje vært bedre å ekskludert slf4j-api bare i de dependenciene som tar den inn, men var så mange at jeg gikk for dette.
> Attempt to fix release script by excluding (and specifying) conflicing dep

- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
Relates to NDLANO/Issues#2416
- Legger til sjekk for article-iframe url'er i læringsstier
> #2416: Use article-iframe aswell when checking usage in learningpaths

- .gitignore
- build.sbt
> #2495: Bump validation

- build.sbt
Bumper validation for å kunne sette inn statisk.ndla.no som iframe i artikkel.
> Bumped validation to get support for ndla-urls

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
Artikler skal kunne forhåndsvises også for status QUEUED_FOR_PUBLISHING_DELAYED.
> Added new status for preview

- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
Fikses https://github.com/NDLANO/Issues/issues/2601
Har testa med å poste med ei tom testfil av type f3d. 
Måtte skifte region til eu-central-1 frå eu-west-1 for å kunne poste filtype.
> Lagt til filtype f3d

- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
Fixes https://github.com/NDLANO/Issues/issues/2640
> Removed h5p success dependency when publishing articles

- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/DraftSwagger.scala
- src/main/scala/no/ndla/draftapi/controller/AgreementController.scala
- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/controller/RuleController.scala
- src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- src/main/scala/no/ndla/draftapi/model/domain/Language.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchService.scala
- src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- src/test/scala/no/ndla/draftapi/TestData.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/service/search/ArticleSearchServiceTest.scala
- src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
NDLANO/Issues#2656
Gjør det mulig å kjøre draft-api for andre.
> Added parameters to config running draft-api in another domain.

- src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- src/main/scala/no/ndla/draftapi/controller/InternController.scala
- src/main/scala/no/ndla/draftapi/model/domain/LanguagelessSearchResult.scala
- src/main/scala/no/ndla/draftapi/model/search/SearchableGrepCode.scala
- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/ReadService.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/main/scala/no/ndla/draftapi/service/search/GrepCodesIndexService.scala
- src/main/scala/no/ndla/draftapi/service/search/GrepCodesSearchService.scala
- src/main/scala/no/ndla/draftapi/service/search/IndexService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/draftapi/service/search/SearchService.scala
- src/test/scala/no/ndla/draftapi/TestEnvironment.scala
- src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- src/test/scala/no/ndla/draftapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/search/GrepCodesIndexServiceTest.scala
- src/test/scala/no/ndla/draftapi/service/search/GrepCodesSearchServiceTest.scala
Fixes NDLANO/Issues#2704
Gjør grepkodesøket til elasticsearch.
Krever indeksering. Blir raskere :^)
> #2704: Convert grep code search to elasticsearch

- build.sbt
> bump validation, add trinket.io as new supported embed type

- src/main/scala/no/ndla/draftapi/controller/InternController.scala
Fixes NDLANO/Issues#2772
Prøvde å se om jeg fant noen måte å gjøre indekseringen raskere, men fant ingen åpenbare ting i alle fall :shrug:
> #2772: Never time out bulk indexing

- src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
Relates to NDLANO/Issues#2786
Kan testes ved å spinne opp lokalt api og sjekke at man får lastet opp en mp4 fil. :shrug:
> #2786: Allow mp4 file upload

- .github/workflows/release.yml
- .github/workflows/typescript-generate.yml
- build.sbt
- build.sh
- project/assembly.sbt
- project/plugins.sbt
Legger til blackbox, og gpg-nøkkel i release-workflow'en for å kunne release med den nye versjonen av deploy med krypterte hemmeligheter.
Testes ved å merge til master :woozy_face:
> Install blackbox and gpg key when releasing

- build.sbt
NDLANO/Issues#2857
Add codepen.io
> Bumped validation

- build.sbt
Oppdaterer til ny validation i forbindelse med NDLANO/Issues#2859. Legger til støtte for flere html-tags.
> Upgrade validation

- src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
- src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
Fixes https://github.com/NDLANO/Issues/issues/2813
All tilbakemelding settes pris på!
> 2813 Endre state-machine basert på articleId

- build.sbt
Relatert til NDLANO/Issues#2859
Legger til class og headers som lovlige attributter i tabell-celler
> Bump validation

- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Fixes NDLANO/Issues#2897
Legger på note dersom artikkel lagres som ny.
> Add note if save as new

- src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- src/main/scala/no/ndla/draftapi/service/WriteService.scala
- src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
- src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Forrige versjon funka ikkje. Noten blei sletta ved opprettelse av ny versjon. Men no skal det fungere.
> Add note when copying article
